package dev.krysztal.casualtiesbelow.datagen

import net.minecraft.core.RegistrySetBuilder
import net.minecraft.core.registries.Registries
import net.minecraft.world.damagesource.DamageEffects
import net.minecraft.world.damagesource.DamageScaling
import net.minecraft.world.damagesource.DamageType
import net.minecraft.world.damagesource.DeathMessageType

import dev.krysztal.casualtiesbelow.damage.CasualtiesBelowDamageTypes

import net.fabricmc.fabric.api.datagen.v1.DataGeneratorEntrypoint
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator

/** Data generation entrypoint (declared as `fabric-datagen` in fabric.mod.json). Run with
  * `./gradlew runDatagen`; output lands in `src/main/generated` and is packaged by Loom.
  */
object CasualtiesBelowDataGenerator extends DataGeneratorEntrypoint {

  override def onInitializeDataGenerator(generator: FabricDataGenerator): Unit = {
    val pack = generator.createPack()
    pack.addProvider[DamageTypeProvider]((output, registries) =>
      new DamageTypeProvider(output, registries)
    )
    pack.addProvider[DamageTypeTagProvider]((output, registries) =>
      new DamageTypeTagProvider(output, registries)
    )
  }

  override def buildRegistry(registryBuilder: RegistrySetBuilder): Unit = {
    registryBuilder.add(
      Registries.DAMAGE_TYPE,
      bootstrap => bootstrap.register(CasualtiesBelowDamageTypes.BloodLoss, BloodLossDamageType)
    )
  }

  /** Fatal blood loss, dealt when the blood volume reaches zero. Sourceless, unscaled, no
    * exhaustion; the bypasses tags are generated by [[DamageTypeTagProvider]].
    */
  private val BloodLossDamageType = new DamageType(
    "blood_loss",
    DamageScaling.NEVER,
    0.0f,
    DamageEffects.HURT,
    DeathMessageType.DEFAULT
  )
}
