package dev.krysztal.casualtiesbelow

import net.minecraft.core.RegistrySetBuilder
import net.minecraft.core.registries.Registries
import net.minecraft.world.damagesource.DamageEffects
import net.minecraft.world.damagesource.DamageScaling
import net.minecraft.world.damagesource.DamageType
import net.minecraft.world.damagesource.DeathMessageType

import net.fabricmc.fabric.api.datagen.v1.DataGeneratorEntrypoint
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator

import dev.krysztal.casualtiesbelow.api.CasualtiesBelowDamageTypes
import dev.krysztal.casualtiesbelow.api.data.CasualtiesBelowRegistries
import dev.krysztal.casualtiesbelow.datagen.BluntMeleeTagProvider
import dev.krysztal.casualtiesbelow.datagen.CasualtiesBelowDataDefaults
import dev.krysztal.casualtiesbelow.datagen.DamageTypeProvider
import dev.krysztal.casualtiesbelow.datagen.DamageTypeTagProvider
import dev.krysztal.casualtiesbelow.datagen.GameplayDataProvider
import dev.krysztal.casualtiesbelow.datagen.ItemTagProvider

/** Data generation entrypoint (declared as `fabric-datagen` in fabric.mod.json). Run with
  * `./gradlew runDatagen`; output lands in `src/main/generated` and is packaged by Loom.
  */
object CasualtiesBelowDataGenerator extends DataGeneratorEntrypoint {

  override def onInitializeDataGenerator(generator: FabricDataGenerator): Unit = {
    val pack = generator.createPack()
    pack.addProvider[DamageTypeProvider]((output, registries) =>
      DamageTypeProvider(output, registries)
    )
    pack.addProvider[DamageTypeTagProvider]((output, registries) =>
      DamageTypeTagProvider(output, registries)
    )
    pack.addProvider[ItemTagProvider]((output, registries) => ItemTagProvider(output, registries))
    pack.addProvider[BluntMeleeTagProvider]((output, registries) =>
      BluntMeleeTagProvider(output, registries)
    )
    pack.addProvider[GameplayDataProvider]((output, registries) =>
      GameplayDataProvider(output, registries)
    )
  }

  override def buildRegistry(registryBuilder: RegistrySetBuilder): Unit = {
    registryBuilder
      .add(
        CasualtiesBelowRegistries.WoundProfile,
        CasualtiesBelowDataDefaults.bootstrapWoundProfiles
      )
      .add(CasualtiesBelowRegistries.WoundRule, CasualtiesBelowDataDefaults.bootstrapWoundRules)
      .add(
        CasualtiesBelowRegistries.ArmorProtection,
        CasualtiesBelowDataDefaults.bootstrapArmorProtection
      )
      .add(CasualtiesBelowRegistries.Discomfort, CasualtiesBelowDataDefaults.bootstrapDiscomfort)
      .add(CasualtiesBelowRegistries.FallRules, CasualtiesBelowDataDefaults.bootstrapFallRules)
      .add(CasualtiesBelowRegistries.HitLocation, CasualtiesBelowDataDefaults.bootstrapHitLocation)

    registryBuilder.add(
      Registries.DAMAGE_TYPE,
      bootstrap => {
        bootstrap.register(CasualtiesBelowDamageTypes.BloodLoss, BloodLossDamageType)
        bootstrap.register(CasualtiesBelowDamageTypes.Sepsis, SepsisDamageType)
        bootstrap.register(CasualtiesBelowDamageTypes.Hypoxia, HypoxiaDamageType)
        bootstrap.register(CasualtiesBelowDamageTypes.Starvation, StarvationDamageType)
      }
    )
  }

  /** Fatal blood loss, dealt when the blood volume reaches zero. Sourceless, unscaled, no
    * exhaustion; the bypasses tags are generated by [[DamageTypeTagProvider]].
    */
  private val BloodLossDamageType = DamageType(
    "blood_loss",
    DamageScaling.NEVER,
    0.0f,
    DamageEffects.HURT,
    DeathMessageType.DEFAULT
  )

  /** Fatal sepsis, dealt when sepsis compresses the effective blood volume cap to zero. */
  private val SepsisDamageType = DamageType(
    "sepsis",
    DamageScaling.NEVER,
    0.0f,
    DamageEffects.HURT,
    DeathMessageType.DEFAULT
  )

  /** Fatal terminal hypoxia after the configured zero-oxygen exposure. */
  private val HypoxiaDamageType = DamageType(
    "hypoxia",
    DamageScaling.NEVER,
    0.0f,
    DamageEffects.HURT,
    DeathMessageType.DEFAULT
  )

  /** Fatal custom starvation after vanilla food cadence drains blood to zero. */
  private val StarvationDamageType = DamageType(
    "starvation",
    DamageScaling.NEVER,
    0.0f,
    DamageEffects.HURT,
    DeathMessageType.DEFAULT
  )
}
