package dev.krysztal.casualtiesbelow.progression

import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries

import dev.krysztal.casualtiesbelow.api.CasualtiesBelowApi

/** The mod's criterion triggers: conditionless player events fired from the physiological hook
  * points that own each condition (see [[AchievementHooks]]). Advancement JSON references them by
  * id under `data/casualtiesbelow/advancement/` (generated by `datagen.AdvancementProvider`).
  */
object CasualtiesBelowTriggers {

  /** Died of terminal hypoxia while opioid respiratory failure was active. */
  val OpioidOverdoseDeath: PlayerEventTrigger = register("opioid_overdose_death")

  /** Consciousness reached literal zero. */
  val ConsciousnessMinimum: PlayerEventTrigger = register("consciousness_minimum")

  /** Eating raised discomfort to the configured maximum. */
  val MaxDiscomfortFood: PlayerEventTrigger = register("max_discomfort_food")

  /** External bleeding was fully stopped after peaking at the near-maximum rate (see
    * [[HemostasisEpisode]]).
    */
  val Hemostasis: PlayerEventTrigger = register("hemostasis")

  private def register(path: String): PlayerEventTrigger = {
    Registry.register(
      BuiltInRegistries.TRIGGER_TYPES,
      CasualtiesBelowApi.id(path),
      new PlayerEventTrigger
    )
  }

  /** Forces static initialization; the triggers self-register. Registered triggers must exist
    * before datapack load validates advancement trigger ids.
    */
  def register(): Unit = ()
}
